import turtle as t
t.penup()
t.goto(-150,150)
t.pendown()
t.color("black","red")
t.begin_fill()
t.left(-180)
t.forward(50)
t.left(90)
t.forward(400)
t.left(90)
t.forward(50)
t.left(90)
t.forward(400)
t.end_fill()

t.penup()
t.goto(150,150)
t.pendown()
t.color("black","red")
t.begin_fill()
t.right(90)
t.forward(50)
t.right(90)
t.forward(400)
t.right(90)
t.forward(50)
t.right(90)
t.forward(400)
t.end_fill()

t.penup()
t.goto(-100,200)
t.pendown()
t.begin_fill()
t.right(90)
t.forward(200)
t.right(90)
t.forward(50)
t.right(90)
t.forward(200)
t.right(90)
t.forward(50)
t.right(90)
t.end_fill()

myfont = "华文行楷" #"隶书" #"楷书" # "行书" #"隶书" # "仿宋"
myfontcolor = "yellow"
fontstyle = "normal" #normal（表示正常）、bold（粗体）、italic（斜体）、underline（下划线）

t.pencolor(myfontcolor)

t.penup()
t.goto(-80,150)
t.pendown()
t.write("阖家幸福",align="left",font=(myfont,30,fontstyle))

t.penup()
t.goto(157,-255)
t.pendown()
t.write("春\n风\n得\n意\n福\n满\n门\n",align="left",font=(myfont,35,fontstyle))

t.penup()
t.goto(-195,-255)
t.pendown()
t.write("天\n增\n岁\n月\n人\n增\n寿\n",align="left",font=(myfont,35,fontstyle))

t.done()